version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8 #corretto11
      
  build:
    commands:
      - mkdir sapjco3
      - aws s3 cp s3://sap-sources/SAPJCO sapjco3/ --recursive
      - chmod 777 sapjco3 -R
      - ls -l
      - ls -l sapjco3
      - sam build
    
#post_build:
#  commands:
    #- sam package --output-template-file packaged.yml --s3-bucket sap-monitor
    #- sam publish --template packaged.yml --region eu-central-1
    #- sam publish --template packaged.yml --region eu-west-1
    #- sam publish --template packaged.yml --region us-east-1
    #- sam publish --template packaged.yml --region us-east-2
    #- sam publish --template packaged.yml --region us-west-1
    #- sam publish --template packaged.yml --region us-west-2

#artifacts:
#  files:
#    - deployspec.yml
#    - packaged.yaml